# Site settings
baseurl = "http://www.biblefoundry.com/"
languageCode = "en-us"
title = "BibleFoundry"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-76623058-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "BibleFoundry"
	description = "Apps to build up the body of Christ"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "biblefoundry@gmail.com"


	# Navigation
	[params.navigation]
		brand = "BibleFoundry"
		logo = "biblefoundry.png"
		apps = "Apps"
		about = "About"
		team = "Our Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    ## postpended links
    #[[menu.postpend]]
    #    url = "http://gohugo.io"
    #    name = "External link"
    #    weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome to BibleFoundry!"
		subtitle = "Apps to build up the body of Christ"
		buttonText = "Tell me more"


	# Apps section
	[params.apps]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Apps"
		subtitle = "Apps released or in development"


    # About section
	[params.about]
        enable = true
		title = "About"
		subtitle = "What we are all about"
		content = "..."


	# Team section
	[params.team]
        enable = true
		title = "Our Team"
		subtitle = "Who we are"

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "bryant.jpg"
			name = "Bryant Huang"
			bio = "Slave of God"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "Keep in touch by sending us a message here"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "&copy; 2016 BibleFoundry"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/BibleFoundry"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/BibleFoundry"
